### ISSUE TITLE
'NoneType' object has no attribute 'get_function'

### ISSUE THREAD

**Issue by sjtuytc** [sniklaus/pytorch-liteflownet#47]
How to address the below error?
My CUPY version is 10.0.0, CUDA version is 10.2
Traceback (most recent call last):
  File "run.py", line 377, in <module>
    tenOutput = estimate(tenOne, tenTwo)
  File "run.py", line 363, in estimate
    tenFlow = torch.nn.functional.interpolate(input=netNetwork(tenPreprocessedOne, tenPreprocessedTwo), size=(intHeight, intWidth), mode='bilinear', align_corners=False)
  File "/data/software/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "run.py", line 325, in forward
    tenFlow = self.netMatching[intLevel](tenOne[intLevel], tenTwo[intLevel], tenFeaturesOne[intLevel], tenFeaturesTwo[intLevel], tenFlow)
  File "/data/software/conda/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "run.py", line 176, in forward
    tenCorrelation = torch.nn.functional.leaky_relu(input=correlation.FunctionCorrelation(tenOne=tenFeaturesOne, tenTwo=tenFeaturesTwo, intStride=1), negative_slope=0.1, inplace=False)
  File "./correlation/correlation.py", line 394, in FunctionCorrelation
    return _FunctionCorrelation.apply(tenOne, tenTwo, intStride)
  File "./correlation/correlation.py", line 297, in forward
    'output': rbot0
  File "cupy/_util.pyx", line 67, in cupy._util.memoize.decorator.ret
  File "./correlation/correlation.py", line 276, in cupy_launch
    return cupy.cuda.compile_with_cache(strKernel).get_function(strFunction)
AttributeError: 'NoneType' object has no attribute 'get_function'

**Comment by sniklaus** [comment]
You are hitting this bug in CuPy which you should be able to resolve be using an older CuPy version: https://github.com/cupy/cupy/issues/6231
