### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'.

### ISSUE THREAD

**Issue by LJNDDUP** [sniklaus/pytorch-liteflownet#5]
I run the command as follows and the following problem. Anyone encountering the same problem?

(base) λ python run.py --model default --first ./images/first.png --second ./images/second.png --out ./out.flo
Traceback (most recent call last):
  File "run.py", line 336, in <module>
    moduleNetwork = Network().cuda().eval()
  File "run.py", line 301, in __init__
    self.load_state_dict(torch.load('./network-' + arguments_strModel + '.pytorch'))
  File "C:\Users\lijianan7\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\serialization.py", line 368, in load
    return _load(f, map_location, pickle_module)
  File "C:\Users\lijianan7\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by sniklaus** [comment]
Have you tried downloading the models again? Also, I see that you are using Windows, which is unfortunately not supported, my apologies.
